//This module is for showing or hiding markers based on what side they belong to.

//ADDMARKER(SIDE, NAME)
//SIDE is the side of the marker, NAME is the name of the marker.
//If you dont want anyone to see the marker use SYSTEM.

//Example:
//ADDMARKER(west, "start");
//ADDMARKER(SYSTEM, "objBravo");

ADDMARKER(west, "marker_138");
ADDMARKER(west, "A 1-18");
ADDMARKER(west, "SCTS 1-18");
ADDMARKER(west, "C 1-18");
ADDMARKER(west, "box");
ADDMARKER(west, "BBS");
ADDMARKER(west, "BBE");
ADDMARKER(west, "BBN");
ADDMARKER(west, "BBW");
ADDMARKER(west, "LB");
ADDMARKER(west, "Trib");
ADDMARKER(west, "Tril");
ADDMARKER(west, "MFP");
ADDMARKER(west, "ATTACK");
ADDMARKER(west, "POS");
ADDMARKER(west, "ATK");
ADDMARKER(west, "VAN");
ADDMARKER(west, "TAA");
ADDMARKER(west, "D 1-18");
ADDMARKER(west, "SBF");
ADDMARKER(west, "SBFM");
ADDMARKER(west, "RIFLES");
ADDMARKER(west, "marker_0");
ADDMARKER(west, "PISTOL");
ADDMARKER(east, "BUNKER1");
ADDMARKER(east, "BUNKER2");
ADDMARKER(east, "BUNKER3");
ADDMARKER(east, "BUNKER4");
ADDMARKER(east, "BUNKER5");
ADDMARKER(west, "marker_25");
ADDMARKER(west, "marker_26");
ADDMARKER(west, "marker_27");
ADDMARKER(west, "marker_28");
ADDMARKER(west, "marker_15");
ADDMARKER(west, "marker_16");
ADDMARKER(west, "marker_17");
ADDMARKER(west, "marker_18");
ADDMARKER(west, "marker_19");
ADDMARKER(west, "marker_20");
ADDMARKER(west, "marker_21");
ADDMARKER(west, "marker_22");
ADDMARKER(east, "OP1");
ADDMARKER(east, "OP2");
ADDMARKER(east, "OP3");
ADDMARKER(east, "tril_3");
ADDMARKER(east, "trib_4");
ADDMARKER(east, "LB_1");
ADDMARKER(east, "MFP 1");
ADDMARKER(east, "RU_EL");
ADDMARKER(east, "PLT");
ADDMARKER(east, "RUDA");
ADDMARKER(east, "BBS_1");
ADDMARKER(east, "BBE_1");
ADDMARKER(east, "BBN_1");
ADDMARKER(east, "BBW_1");
ADDMARKER(east, "ZONE");
ADDMARKER(west, "marker_143");
ADDMARKER(west, "marker_188");
ADDMARKER(east, "marker_189");
ADDMARKER(east, "A 1-18_1");
ADDMARKER(west, "marker_191");
ADDMARKER(west, "marker_192");
ADDMARKER(west, "marker_194");
ADDMARKER(east, "KEY1");
ADDMARKER(east, "KEY2");
ADDMARKER(east, "marker_201");
ADDMARKER(east, "marker_202");
ADDMARKER(east, "marker_203");
ADDMARKER(east, "marker_204");
ADDMARKER(east, "marker_205");
ADDMARKER(east, "marker_206");
ADDMARKER(east, "marker_208");
ADDMARKER(east, "marker_209");
ADDMARKER(east, "marker_210");
ADDMARKER(east, "marker_211");
ADDMARKER(east, "marker_212");
ADDMARKER(east, "marker_213");
ADDMARKER(east, "marker_214");
ADDMARKER(east, "marker_215");
ADDMARKER(east, "marker_216");
ADDMARKER(east, "marker_207");
ADDMARKER(east, "marker_217");
ADDMARKER(east, "marker_218");
ADDMARKER(east, "marker_219");
ADDMARKER(east, "marker_220");
ADDMARKER(east, "marker_221");
ADDMARKER(east, "marker_222");
ADDMARKER(east, "marker_223");
ADDMARKER(east, "marker_224");
ADDMARKER(east, "marker_249");
ADDMARKER(east, "marker_250");
ADDMARKER(east, "marker_251");
ADDMARKER(east, "marker_237");
ADDMARKER(east, "marker_252");
ADDMARKER(east, "marker_253");
ADDMARKER(east, "marker_254");
ADDMARKER(east, "marker_255");
ADDMARKER(east, "marker_246");
ADDMARKER(east, "marker_238");
ADDMARKER(east, "marker_239");
ADDMARKER(east, "marker_247");
ADDMARKER(east, "marker_248");
ADDMARKER(east, "marker_240");
ADDMARKER(east, "marker_241");
ADDMARKER(east, "marker_242");
ADDMARKER(east, "marker_243");
ADDMARKER(east, "marker_245");
ADDMARKER(east, "marker_236");
ADDMARKER(east, "marker_225");
ADDMARKER(east, "marker_226");
ADDMARKER(east, "marker_227");
ADDMARKER(east, "marker_228");
ADDMARKER(east, "marker_229");
ADDMARKER(east, "marker_230");
ADDMARKER(east, "marker_231");
ADDMARKER(east, "marker_232");
ADDMARKER(east, "marker_233");
ADDMARKER(east, "marker_256");
ADDMARKER(east, "marker_257");
ADDMARKER(east, "marker_258");
ADDMARKER(east, "marker_259");
ADDMARKER(east, "marker_260");
ADDMARKER(east, "marker_261");
ADDMARKER(east, "marker_262");